CODE SEGMENT
ASSUME CS:CODE, DS:CODE
MOV AX,CS ; DS설정
MOV DS,AX
;
MOV CX,100 ; CX에 100을 지정
MOV AX,0 ; AX 에 0을 지정
NEXT: ADD AX,CX
SUB CX,1
CMP CX,0; CX의 내용이 0인가 비교
JNE NEXT;0이면 밑으로 아니면 NEXT 라는 라벨로 이동
MOV TOTAL,AX
MOV AH,4CH ;끝내고 MS-DOS로 돌아간다.
INT 21H
;
TOTAL DW ?
CODE ENDS
END